"""Independent small exhaustive checks for the deterministic prefix frontier.

Full arrangements are generated by permutations/products rather than by the
planner's child expansion, then seam-matched by scalar reversed-bit strings.
No CUDA runtime or active solver state is touched.
"""
import datetime
import hashlib
import itertools
import json
from pathlib import Path
import platform
import sys
import time
import unittest

import numpy as np

from exact_frontier import plan_frontier

ROOT = Path(__file__).resolve().parent


def open_fixture(count=3, rotations=3):
    return (np.zeros((count * rotations, 1), np.uint16),
            np.full((count, 1), -1, np.int16),
            np.full((count, 1), -1, np.int16),
            np.arange(count, dtype=np.int16))


def ring_fixture():
    count = 4
    neighbors = np.full((count, 3), -1, np.int16)
    sides = neighbors.copy()
    edges = [1, 2, 4, 3]
    masks = np.empty((count * 3, 3), np.uint16)
    for cell in range(count):
        neighbors[cell, :2] = ((cell - 1) % count, (cell + 1) % count)
        sides[cell, :2] = (1, 0)
        incoming = int(f'{edges[(cell - 1) % count]:03b}'[::-1], 2)
        base = [incoming, edges[cell], 0]
        for rotation in range(3):
            masks[3 * cell + rotation] = np.roll(base, rotation)
    return masks, neighbors, sides, np.array([2, 0, 3, 1], np.int16)


def all_arrangements(count, rotations):
    for permutation in itertools.permutations(range(count)):
        for orientations in itertools.product(range(rotations), repeat=count):
            yield tuple(tile * rotations + rotation
                        for tile, rotation in zip(permutation, orientations))


def independently_compatible(codes, masks, neighbors, sides, width):
    for cell, row in enumerate(neighbors):
        for side, other in enumerate(row):
            other = int(other)
            if other >= 0:
                adjacent = int(masks[codes[other], int(sides[cell, side])])
                reversed_mask = int(format(adjacent, f'0{width}b')[::-1], 2)
                if int(masks[codes[cell], side]) != reversed_mask:
                    return False
    return True


def prefixes_of(plan):
    return [tuple(map(int, row[:int(length)]))
            for row, length in zip(plan.prefixes, plan.lengths)]


class ExactFrontierTests(unittest.TestCase):
    def assert_cover(self, fixture, plan, rotations=3, width=11):
        masks, neighbors, sides, order = fixture
        count = len(order)
        prefixes = prefixes_of(plan)
        self.assertEqual(len(prefixes), len(set(prefixes)))
        for first, second in itertools.combinations(prefixes, 2):
            self.assertFalse(first == second[:len(first)])
            self.assertFalse(second == first[:len(second)])
        for prefix, row in zip(prefixes, plan.prefixes):
            self.assertTrue(np.all(row[len(prefix):] == -1))
            self.assertEqual(len({code // rotations for code in prefix}), len(prefix))
        covered_raw = 0
        valid_boards = 0
        for codes in all_arrangements(count, rotations):
            ordered = tuple(codes[int(cell)] for cell in order)
            matches = sum(ordered[:len(prefix)] == prefix for prefix in prefixes)
            self.assertLessEqual(matches, 1, 'A full arrangement belongs to multiple jobs')
            covered_raw += matches
            if independently_compatible(codes, masks, neighbors, sides, width):
                valid_boards += 1
                self.assertEqual(matches, 1, 'An edge-compatible arrangement was omitted')
        metadata = plan.metadata
        self.assertTrue(metadata['cover_complete'])
        self.assertEqual(int(metadata['raw_arrangements_remaining']), covered_raw)
        self.assertEqual(int(metadata['raw_arrangements_total']),
                         int(metadata['raw_arrangements_pruned']) + covered_raw)
        return valid_boards

    def test_disjoint_cover_and_raw_partition_at_several_targets(self):
        fixture = ring_fixture()
        for target in (1, 2, 15, 50, 5000):
            with self.subTest(target=target):
                plan = plan_frontier(*fixture, target, mask_width=3)
                valid = self.assert_cover(fixture, plan, width=3)
                self.assertGreater(valid, 0)
                self.assertLessEqual(len(plan.lengths), target + len(fixture[0]) - 1)

    def test_variable_depth_prefixes_preserve_all_siblings(self):
        fixture = open_fixture()
        plan = plan_frontier(*fixture, 20)
        self.assertEqual(len(plan.lengths), 24)
        self.assertEqual(set(map(int, plan.lengths)), {1, 2})
        self.assert_cover(fixture, plan)
        self.assertEqual(plan.metadata['raw_arrangements_pruned'], '0')

    def test_full_length_leaves_are_retained_as_jobs(self):
        fixture = open_fixture(rotations=2)
        plan = plan_frontier(*fixture, 100, rotations=2)
        self.assertEqual(len(plan.lengths), 48)
        self.assertTrue(np.all(plan.lengths == 3))
        self.assertEqual(plan.metadata['stop_reason'], 'fully_expanded')
        self.assertTrue(plan.metadata['all_jobs_complete_boards'])
        self.assertEqual(plan.metadata['complete_board_jobs'], 48)
        self.assert_cover(fixture, plan, rotations=2)

    def test_incompatible_children_can_exhaust_frontier(self):
        masks = np.ones((6, 1), np.uint16)
        neighbors = np.array([[1], [0]], np.int16)
        sides = np.zeros((2, 1), np.int16)
        fixture = masks, neighbors, sides, np.arange(2, dtype=np.int16)
        plan = plan_frontier(*fixture, 100, mask_width=2)
        self.assertEqual(plan.prefixes.shape, (0, 2))
        self.assertTrue(plan.metadata['exhausted'])
        self.assertEqual(plan.metadata['stop_reason'], 'exhausted')
        self.assertEqual(plan.metadata['raw_arrangements_pruned'], '18')
        self.assertEqual(self.assert_cover(fixture, plan, width=2), 0)

    def test_cancellation_returns_complete_unsplit_cover(self):
        fixture = ring_fixture()
        callbacks = []
        cancel = {'value': False}

        def progress(metadata):
            callbacks.append(metadata)
            if metadata['expanded_prefixes'] >= 2:
                cancel['value'] = True

        plan = plan_frontier(*fixture, 5000, mask_width=3, progress_every=1,
                             progress=progress, stop_requested=lambda: cancel['value'])
        self.assertEqual(plan.metadata['stop_reason'], 'cancelled')
        self.assertEqual(plan.metadata['expanded_prefixes'], 2)
        self.assertGreaterEqual(len(callbacks), 3)
        self.assertEqual(callbacks[0]['expanded_prefixes'], 0)
        self.assertEqual(callbacks[-1], plan.metadata)
        self.assert_cover(fixture, plan, width=3)

    def test_initial_cancel_retains_zero_length_root(self):
        fixture = open_fixture()
        plan = plan_frontier(*fixture, 100, stop_requested=lambda: True)
        self.assertEqual(prefixes_of(plan), [()])
        self.assertEqual(plan.metadata['stop_reason'], 'cancelled')
        self.assert_cover(fixture, plan)

    def test_job_cap_does_not_keep_only_some_children(self):
        fixture = open_fixture()
        plan = plan_frontier(*fixture, 10, max_jobs=4)
        self.assertEqual(prefixes_of(plan), [()])
        self.assertEqual(plan.metadata['stop_reason'], 'job_limit')
        self.assertEqual(plan.metadata['expanded_prefixes'], 0)
        self.assert_cover(fixture, plan)

    def test_memory_cap_retains_parent_and_accounts_for_output(self):
        fixture = open_fixture()
        plan = plan_frontier(*fixture, 100, max_frontier_bytes=500)
        self.assertEqual(prefixes_of(plan), [()])
        self.assertEqual(plan.metadata['stop_reason'], 'memory_limit')
        self.assertLessEqual(plan.metadata['charged_frontier_bytes'], 500)
        self.assert_cover(fixture, plan)
        with self.assertRaisesRegex(ValueError, 'root'):
            plan_frontier(*fixture, 100, max_frontier_bytes=1)

    def test_expansion_cap_returns_complete_frontier(self):
        fixture = ring_fixture()
        plan = plan_frontier(*fixture, 5000, max_expansions=3, mask_width=3)
        self.assertEqual(plan.metadata['stop_reason'], 'expansion_limit')
        self.assertEqual(plan.metadata['expanded_prefixes'], 3)
        self.assert_cover(fixture, plan, width=3)

    def test_lookup_cache_eviction_changes_no_jobs_or_pruning(self):
        fixture = ring_fixture()
        plans = [plan_frontier(*fixture, 5000, mask_width=3, candidate_cache_entries=limit)
                 for limit in (0, 1, 4096)]
        for plan in plans[1:]:
            np.testing.assert_array_equal(plan.prefixes, plans[0].prefixes)
            np.testing.assert_array_equal(plan.lengths, plans[0].lengths)
            self.assertEqual(plan.metadata['raw_arrangements_pruned'],
                             plans[0].metadata['raw_arrangements_pruned'])
        self.assertEqual(plans[0].metadata['candidate_cache_entries'], 0)
        self.assertLessEqual(plans[1].metadata['candidate_cache_entries'], 1)

    def test_deterministic_hashes_independent_of_input_integer_dtype(self):
        fixture = ring_fixture()
        first = plan_frontier(*fixture, 20, mask_width=3)
        second = plan_frontier(*(array.astype(np.int64) for array in fixture),
                               20, mask_width=3)
        self.assertEqual(first.metadata, second.metadata)
        np.testing.assert_array_equal(first.prefixes, second.prefixes)
        changed_order = (*fixture[:3], fixture[3][::-1])
        third = plan_frontier(*changed_order, 20, mask_width=3)
        self.assertEqual(first.metadata['puzzle_sha256'], third.metadata['puzzle_sha256'])
        self.assertNotEqual(first.metadata['order_sha256'], third.metadata['order_sha256'])

    def test_input_validation_rejects_ambiguous_or_invalid_domains(self):
        fixture = ring_fixture()
        with self.assertRaisesRegex(ValueError, 'target_jobs'):
            plan_frontier(*fixture, True)
        with self.assertRaisesRegex(ValueError, 'order'):
            plan_frontier(*fixture[:3], [0, 1, 1, 3], 10)
        with self.assertRaisesRegex(ValueError, 'reciprocal'):
            sides = fixture[2].copy()
            sides[0, 0] = 0
            plan_frontier(fixture[0], fixture[1], sides, fixture[3], 10)
        with self.assertRaisesRegex(ValueError, 'integers'):
            plan_frontier(fixture[0].astype(float), *fixture[1:], 10)
        with self.assertRaisesRegex(ValueError, 'bit width'):
            plan_frontier(*fixture, 10, mask_width=1)
        with self.assertRaisesRegex(ValueError, 'dimensions'):
            plan_frontier(fixture[0][:-1], *fixture[1:], 10)


if __name__ == '__main__':
    names = ('exact_frontier.py', 'test_exact_frontier.py')
    def hashes():
        return {name: hashlib.sha256((ROOT / name).read_bytes()).hexdigest() for name in names}
    before = hashes()
    started_at = datetime.datetime.now(datetime.timezone.utc).isoformat()
    started = time.monotonic()
    suite = unittest.defaultTestLoader.loadTestsFromModule(sys.modules[__name__])
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    after = hashes()
    report = {
        'passed': result.wasSuccessful(), 'tests_run': result.testsRun,
        'failures': len(result.failures), 'errors': len(result.errors),
        'started_at': started_at, 'runtime_seconds': time.monotonic() - started,
        'command': list(sys.orig_argv), 'working_directory': str(ROOT),
        'exit_status': 0 if result.wasSuccessful() else 1,
        'python': sys.version, 'platform': platform.platform(),
        'scope': 'Small exact enumeration (at most 4 tiles and 3 rotations); no puzzle solution or exhaustive 160-tile completion claim',
        'source_sha256_before': before, 'source_sha256_after': after,
        'execution_sources_unchanged': before == after,
    }
    (ROOT / 'exact-frontier-tests.json').write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
    raise SystemExit(report['exit_status'])
